### ISSUE TITLE
Callback queries with unknown parameters

### ISSUE THREAD

**Issue by soend** [vova-lantsov-dev/telegram-bot-helper#1]
Hei, im having trouble getting this to work. Maybe you can point me to right direction. I have callback query `datepicker~{year}~{month}~{day}`. So i followed the example and have it set up:
```
i["datepicker~ "] = async (q, c, _) =>
{
     ... do something.
};
```
What could i be doing wrong?

**Comment by soend** [comment]
I think i figured out the issue. When registering inline action with 3 unknown parameters it should look like this:
```
i["datepicker~ ~ ~ "] = async (q, c, _) =>
{
     ... do something.
};
```

And also there is bug here: https://github.com/vova-lantsov-dev/telegram-bot-helper/blob/7bb6eb3924aad9dbcbac86ed18d230e590d07dcc/InlineCommand.cs#L32

Correct should be like this:
`if (string.IsNullOrWhiteSpace(valueToCompareWith.Commands[commandIndex]))`

**Comment by vova-lantsov-dev** [comment]
@soend yes, you are right, this bug is already fixed and will be resolved in next release
