### ISSUE TITLE
NuGet package installation(.Net framework 4.5 doesn't supported)

### ISSUE THREAD

**Issue by michaelkhany** [vova-lantsov-dev/telegram-bot-helper#2]
**Installing 'Telegram.Bot.Helper 1.0.3'.**
Successfully installed 'Telegram.Bot.Helper 1.0.3'.
Adding 'Telegram.Bot.Helper 1.0.3' to TGPie.
**Uninstalling 'Telegram.Bot.Helper 1.0.3'.**
Successfully uninstalled 'Telegram.Bot.Helper 1.0.3'.
**Install failed. Rolling back...**
Could not install package 'Telegram.Bot.Helper 1.0.3'. You are trying to install this package into a project that targets '**.NETFramework,Version=v4.5**', but the **package does not contain any assembly references or content files that are compatible with that framework**. For more information, contact the package author.

**Comment by vova-lantsov-dev** [comment]
@michaelkhany to use my library you must have at least .NET Framework 4.6.1

**Comment by vova-lantsov-dev** [comment]
Support for previous versions of .NET Framework is not planned.
